config/routes.rb
Contest::Application.routes.draw do
  resources :quizzes

  get "home/index"

  root :to => 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :quiz_id, :answers_attributes
  belongs_to :quiz
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  attr_accessible :name, :questions_attributes
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quizzes }
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/new
  # GET /quizzes/new.json
  def new
    @quiz = Quiz.new
    3.times do
      question = @quiz.questions.build
      4.times { question.answers.build }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quiz }
    end
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = Quiz.find(params[:id])
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(params[:quiz])

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render json: @quiz, status: :created, location: @quiz }
      else
        format.html { render action: "new" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quizzes/1
  # PUT /quizzes/1.json
  def update
    @quiz = Quiz.find(params[:id])

    respond_to do |format|
      if @quiz.update_attributes(params[:quiz])
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_remove_fields (name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")		
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/home/index.html.erb
<h1>Contests2win</h1>
<p>Click on link below to show all quizzes.</p>

<%= link_to "List all Quizzes", quizzes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quizzes/_answer_fields.html.erb
<p class="fields">
	<%= f.label :content, "Answer" %>
	<%= f.text_field :content %>
	<%= link_to_remove_fields "remove", f %>
</p>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', :f => builder %> 
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/_question_fields.html.erb
<div class="fields">
	<p>
	  <%= f.label :content, "Question" %>
	  <%= link_to_remove_fields "remove", f %><br />
	  <%= f.text_area :content, :rows => 3 %>
	</p>
	<%= f.fields_for :answers do |builder| %>
	  <%= render 'answer_fields', :f => builder %>
	<% end %>
</div>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Listing quizzes</h1>

<ol>
  <% @quizzes.each do |quiz| %>
    <div>
        <li><strong>Description:</strong><%= quiz.name %></li>
      <%= link_to 'Show', quiz %>
      <%= link_to 'Edit', edit_quiz_path(quiz) %>
      <%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <br />
  <% end %>
</ol>


<br />

<%= link_to 'New Quiz', new_quiz_path %> |
<%= link_to 'Back', home_index_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @quiz.name %>
</p>
<ol>
	<% @quiz.questions.each do |question| %>
		<li><%= question.content %></li>
		<ul>
		    <% question.answers.each do |answer| %>
		      <li><%= answer.content %></li>
		    <% end %>
		</ul>
	<% end %>
</ol>


<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>